### ISSUE TITLE
Chunker error with Box remote

### ISSUE THREAD

**Issue by mwcole** [ivandeex/rclone#19]
#### What is the problem you are having with rclone?

Very cool new feature! Thanks for your help with getting it working.

I get the following error when transferring a large file using the default settings with the chunker backend, with a Box remote repository:
DEBUG : projects/archive/INDIVGraphTheory.tar.gz__tmp.1564856403.001: Cancelling multipart upload: multipart upload failed to read source: EOF

#### What is your rclone version (output from `rclone version`)

rclone v1.48.mr02
- os/arch: linux/amd64
- go version: go1.12.6

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

Linux CentOS 7, 64 bit

####  Which cloud storage system are you using? (eg Google Drive)

Box

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

rclone sync / Chunker_Box_ProjectBackups_RawDataAndDocsDirs: -vv --log-file=logs/chunker_box_projectsrawdataanddocsdirs.log --filter-from FILTERFROM_projectsrawdataanddocsdirs_archiveonly.txt --copy-links --retries 1 --progress

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

Attached. Note that I cancelled the process for this log since it would keep retrying but fail after the last attempt.

[chunker_box_projectsrawdataanddocsdirs_2019-08-04T07:48_mod.log](https://github.com/ivandeex/rclone/files/3464869/chunker_box_projectsrawdataanddocsdirs_2019-08-04T07.48_mod.log)

**Comment by ivandeex** [comment]
I will not have access to desktop for 10 or more days. Sorry for long radio silence.

**Comment by ivandeex** [comment]
Hi Michael
Chunker backend internally streams a file being split and consequently fails if an
underlying remote switches to multipart mode, (aka "parallel upload", which is
confusingly called "chunking mode" somewhere in the rclone documentation).
To work around problems with multipart upload and chunker, you should
make multipart upload cutoff at least as large as the chunker chunk size, eg:
```./rclone copy big.dat BoxChunkerRemote: --box-upload-cutoff=100M --chunker-chunk-size=100M```
In future Chunker may implement some kind of on-disk caching to overcome this issue.

**Comment by mwcole** [comment]
I tested your suggested solution and it worked. Thanks!
